
version: 2

sources:
    - name: raw
      schema : gz_raw_data
      description: greenweez raw data source
      tables:
        - name: sales
          identifier: raw_gz_sales
          description: sales of greenweez
          tests:
            - unique: 
                column_name: "(date_date || '-' || orders_id || '-' || pdt_id)"
          freshness: 
            warn_after: {count: 90, period: day}
          loaded_at_field: "CAST(date_date as TIMESTAMP)"
          columns:
            - name: date_date
              description: date of purchase and primary key
              tests:
                - not_null
            - name: orders_id
              description: orders id and primary key
              tests:
                - not_null
            - name: pdt_id
              description: product id and primary key
              tests:
                - not_null
            - name: revenue
              description: revenue of sales
            - name: quantity
              description: quantity of sales          
        - name: product
          identifier: raw_gz_product
          description: products of greenweez
          columns:
            - name: products_id
              description: products id and primary key
              tests:
                - unique
                - not_null
            - name: purchase_price
              description: purchase price of the product
        - name: ship
          identifier: raw_gz_ship
          description: ship of greenweez
          columns:
            - name: orders_id
              description: orders id and primary key
              tests:
                - unique
                - not_null
            - name: shipping_fee
              description: shipping fee
            - name: logcost
              description: logcost
            - name: ship_cost
              description: ship cost
        - name: adwords
          identifier: raw_gz_adwords
          description: campaign adwords
          tests:
            - unique: 
                column_name: "(date_date || '-' || camPGN_name)"
          columns:
            - name: date_date
              description: campaign date and primary key
              tests:
                - not_null
            - name: paid_source
              description: adwords 
            - name: campaign_key
              description: campaign id 
            - name: camPGN_name
              description: campaign name and primary key
              tests:
                - not_null
            - name: ads_cost
              description: ads cost
            - name: impression
              description: nb of impressions
            - name: click
              description: nb of clicks
        - name: bing
          identifier: raw_gz_bing
          description: campaign bing
          tests:
            - unique: 
                column_name: "(date_date || '-' || camPGN_name)"
          columns:
            - name: date_date
              description: campaign date and primary key
              tests:
                - not_null
            - name: paid_source
              description: bing 
            - name: campaign_key
              description: campaign id 
            - name: camPGN_name
              description: campaign name and primary key
              tests:
                - not_null
            - name: ads_cost
              description: ads cost
            - name: impression
              description: nb of impressions
            - name: click
              description: nb of clicks
        - name: criteo
          identifier: raw_gz_criteo
          description: campaign criteo
          tests:
            - unique: 
                column_name: "(date_date || '-' || camPGN_name)"
          columns:
            - name: date_date
              description: campaign date and primary key
              tests:
                - not_null
            - name: paid_source
              description: criteo 
            - name: campaign_key
              description: campaign id 
            - name: camPGN_name
              description: campaign name and primary key
              tests:
                - not_null
            - name: ads_cost
              description: ads cost
            - name: impression
              description: nb of impressions
            - name: click
              description: nb of clicks
        - name: facebook
          identifier: raw_gz_facebook
          description: campaign facebook
          tests:
            - unique: 
                column_name: "(date_date || '-' || camPGN_name)"
          columns:
            - name: date_date
              description: campaign date and primary key
              tests:
                - not_null
            - name: paid_source
              description: facebook 
            - name: campaign_key
              description: campaign id 
            - name: camPGN_name
              description: campaign name and primary key
              tests:
                - not_null
            - name: ads_cost
              description: ads cost
            - name: impression
              description: nb of impressions
            - name: click
              description: nb of clicks

models:
  - name: int_campaigns
    tests:
      - unique:
          column_name: "(date_date || '-' || paid_source || '-' || campaign_key || '-' || campaign_name)"
    columns:
            - name: date_date
              description: campaign date and primary key
              tests:
                - not_null
            - name: paid_source
              description: campaigns and primary key
              tests:
                - not_null
            - name: campaign_key
              description: campaign id and primary key
              tests:
                - not_null
            - name: campaign_name
              description: campaign name and primary key
              tests:
                - not_null
            - name: ads_cost
              description: ads cost
            - name: impression
              description: nb of impressions
            - name: click
              description: nb of clicks
  - name: int_campaigns_day
    columns:
            - name: date_date
              description: campaign date and primary key
              tests:
                - unique
                - not_null
            - name: ads_cost
              description: ads cost
            - name: ads_impression
              description: nb of impressions
            - name: ads_clicks
              description: nb of clicks